---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  ignore_errors: "{{ ansible_check_mode }}"

- name: Enable Nginx site configuration
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx
  ignore_errors: "{{ ansible_check_mode }}"

- name: Deploy web application
  template:
    src: index.html.j2
    dest: /var/www/html/index.html