---
- name: Install MariaDB and dependencies
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Set MariaDB root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create .my.cnf file for root
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    mode: '0600'
  become: yes

- name: Configure MariaDB
  template:
    src: mysql.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
  notify: restart mysql

- name: Create database
  mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding }}"
    collation: "{{ item.collation }}"
    state: present
  loop: "{{ mysql_databases }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create database users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    host: "{{ item.host }}"
    state: present
  loop: "{{ mysql_users }}"
  ignore_errors: "{{ ansible_check_mode }}"