# all.yml
---
ansible_python_interpreter: /usr/bin/python3
project_name: tp-cloud
env: production
ssh_port: 22
timezone: Europe/Paris
flask_port: 8000

db_port: 3306
db_name: student_db
db_user: backend_user
db_password: "secure_password"

packages_common:
  - vim
  - curl
  - htop
  - net-tools