---
- name: Create app user
  user:
    name: "{{ app_user }}"
    system: yes

- name: Create app directory
  file:
    path: "{{ app_directory }}"
    state: directory
    owner: "{{ app_user }}"

- name: Install Python and pip
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install Python requirements
  pip:
    name: "{{ requirements }}"
    state: present
    executable: pip3
  ignore_errors: "{{ ansible_check_mode }}"

- name: Deploy Flask application
  template:
    src: app.py.j2
    dest: "{{ app_directory }}/app.py"

- name: Create systemd service file
  template:
    src: flask-app.service.j2
    dest: /etc/systemd/system/flask-app.service
    mode: '0755'
  become: yes

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable flask-app.service
  service:
    name: flask-app.service
    enabled: yes
    state: started
