---
- name: Apply common configuration
  hosts: all
  become: yes
  roles:
    - common

- name: Configure frontend servers
  hosts: frontend
  become: yes
  roles:
    - frontend
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

- name: Configure backend servers
  hosts: backend
  become: yes
  roles:
    - backend
  tasks:
    - name: Install python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

- name: Configure database servers
  hosts: database
  become: yes
  roles:
    - database
  tasks:
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

- name: Configure application
  hosts: all
  become: yes
  tasks:
    - name: Wait for all services
      wait_for:
        host: "{{ item }}"
        port: "{{ hostvars[item]['service_port'] }}"
        timeout: 300
      loop: "{{ groups['all'] }}"
      delegate_to: localhost
      run_once: true

    - name: Verify application status
      uri:
        url: "http://{{ hostvars[groups['frontend'][0]]['ansible_host'] }}"
        return_content: yes
      register: app_status
      delegate_to: localhost
      run_once: true
      tags: ['verify']