# site.yml
- name: Apply common configuration
  hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - common

- name: Configure frontend servers
  hosts: frontend
  become: yes
  vars_files:
    - group_vars/frontend.yml
  roles:
    - frontend
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

- name: Configure backend servers
  hosts: backend
  become: yes
  vars_files:
    - group_vars/backend.yml
  roles:
    - backend
  tasks:
    - name: Install python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

- name: Configure database servers
  hosts: database
  become: yes
  vars_files:
    - group_vars/database.yml
  roles:
    - database
  tasks:
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present